export const NOT_FOUND = "%s not exist."
export const MUST_BE_DIRECTORY = "Expect giving path: %s is a directory."
export const MISSING_INDEX_FILE = "Cannot resolve %s, \nFor using POZ, the root folder of your POZ package must contain a file named 'poz.js'"
export const MISSING_TEMPLATE_DIRECTORY = "Cannot resolve %s, \nFor using POZ, A POZ template package should contains a %s directory which used to store the template files. or if your package doesn't need template, you can set noTemplate = true."
export const UNEXPECTED_INDEX_FILE = "Entry file %s must export a plain object or function."
export const CANNOT_EXPORT_EMPTY_OBJECT = "Entry file '%s' cannot export an empty plain object."
export const ENTRY_FILE_THROW_ERROR = "This is probably the problem of '%s'. Please check it."
